In [8]:
import pandas as pd
import numpy as np

In [9]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [10]:
mylist = [[1,2,3],[4,5,6],[6,7,8]]

In [13]:
mymatrix = np.array(mylist)

In [17]:
np.arange(0,11,3) 



array([0, 3, 6, 9])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((5,5)) + 6

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [22]:
np.ones(4) * 100 

array([100., 100., 100., 100.])

In [24]:
np.ones(4)[1] * 2

2.0

In [28]:
gifits = np.ones(8)[4] / 10 

0.01

In [29]:
##for linearly spaced array
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [30]:
#to create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
## creating random numbers
np.random.rand(4,4)

array([[0.14631746, 0.84725745, 0.09394003, 0.33966319],
       [0.74179635, 0.08279918, 0.17078246, 0.62052515],
       [0.66782283, 0.56956044, 0.90717255, 0.22834631],
       [0.73600871, 0.11411509, 0.14679412, 0.89833829]])

In [33]:
#standard normal distribution
np.random.randn(10)

array([-0.27627152, -1.73334031,  0.60736338, -0.19219075, -0.23414333,
       -0.97731818,  1.98415522, -1.51776446,  0.6988479 ,  2.03217604])

In [34]:
np.random.randint(1, 100, 10)

array([59, 29, 76, 61, 25, 19, 87, 25, 16,  2])

In [37]:
np.random.seed(12)
np.random.rand(4)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [47]:
##how to reshape
arr1 = np.arange(28)
reshape = arr1.reshape(7,4)
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [39]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [45]:
reshape.max()

19

In [48]:
### return the index locaition of the maximumm and minimum value
reshape.argmax()

27

In [49]:
reshape.argmin()

0

In [52]:
randomly = np.random.randn(27)
randomly

array([-0.03920917,  0.21497595, -0.3843588 , -0.25390408,  0.07325207,
       -0.99720384, -0.71385629,  0.03541635, -0.67794537, -0.57188106,
       -0.10586232,  1.33583134,  0.31866529, -0.33759525, -0.58526828,
       -0.11491994,  2.24181779, -3.14741652,  0.53513589,  0.23249044,
        0.86761195, -1.14821271,  2.11434424,  1.00094276, -0.051415  ,
        0.1597877 , -0.71626359])

In [53]:
randomly.argmax() #index of the maximum number


16

In [54]:
array1 = np.arange(1,11)

In [55]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
array1[1:7]

array([2, 3, 4, 5, 6, 7])

In [61]:
mult_by_three = array1**3

In [59]:
divide_by_ten = array1/10
divide_by_ten

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [62]:
(mult_by_three)*4 + divide_by_ten

array([   4.1,   32.2,  108.3,  256.4,  500.5,  864.6, 1372.7, 2048.8,
       2916.9, 4001. ])

In [75]:
array2 = np.arange(1,20)

In [76]:
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [78]:
slice_array = array2[1:10]
slice_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
slice_array[:] = 20

In [80]:
array2

array([ 1, 20, 20, 20, 20, 20, 20, 20, 20, 20, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [81]:
array2_copy = array2.copy()
array2_copy[:] = 19

In [82]:
array2_copy

array([19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19])

In [83]:
array2

array([ 1, 20, 20, 20, 20, 20, 20, 20, 20, 20, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [85]:
###indexing on a 2d array
array_3 = np.array([[5,10,15],[20,25,30],[30,35,40]])

In [86]:
array_3

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [87]:
array_3[2][2] = 16

In [88]:
array_3

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 16]])

In [89]:
array_3[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [91]:
array_3[:2, 1:]

array([[10, 15],
       [25, 30]])

In [106]:
np.random.seed(7)
sample_array = np.random.rand(6,6)
sample_array[0:3]

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951,
        0.53849587],
       [0.50112046, 0.07205113, 0.26843898, 0.4998825 , 0.67923   ,
        0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353, 0.21338535,
        0.45212396]])

In [107]:
sample_array[0:3, 2:]

array([[0.43840923, 0.72346518, 0.97798951, 0.53849587],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.2881456 , 0.90959353, 0.21338535, 0.45212396]])

In [120]:
### conditional selection
arr3 = np.arange(10)

In [116]:
arr3[arr3 > 3]

array([4, 5, 6, 7, 8, 9])

In [118]:
###Numpy operations

sample_array2 = np.arange(20)
sample_array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
np.sqrt(sample_array2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.cos(